# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('csaving', models.IntegerField()),
                ('pmsaving', models.IntegerField()),
                ('durinv', models.IntegerField()),
                ('preference', models.CharField(max_length=100)),
                ('risk', models.IntegerField()),
            ],
        ),
    ]
