# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='bank',
            new_name='types',
        ),
        migrations.AddField(
            model_name='insurance',
            name='company',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
