# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('avg_price', models.IntegerField()),
                ('avg_growth', models.FloatField(blank=True, default=None, null=True)),
                ('amount_upto', models.IntegerField()),
                ('types', models.CharField(max_length=50)),
            ],
        ),
    ]
