# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('bank', models.CharField(max_length=20)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('interest', models.FloatField(blank=True, default=None, null=True)),
                ('amount_upto', models.IntegerField()),
            ],
        ),
    ]
